### ISSUE TITLE
Error en sentencia st_write

### ISSUE THREAD

**Issue by MirelSIG** [maestria-geotel-master/unidad-1-asignacion-2-rasters-y-exportar-datos-espaciales-en-r#1]
> st_write <- (obj=miprov,dsn ='data/divisionRD.gpkg', driver ='miprovexportado.gpkg')
Error: unexpected ',' in "st_write <- (obj=miprov,"

**Comment by geofis** [comment]
Je je, aunque no asigné esta práctica aún, ya veo que te adelantaste. Pues qué bien. El fallo radica en que la función `st_write` no se asigna, sino que se usa para crear una salida. Por lo tanto, quedaría tal que esto (nota que después de la función viene paréntesis, no operador de asignación) `st_write(obj=miprov, dsn='...`

**Comment by geofis** [comment]
¿Podemos cerrar este *issue*?

**Comment by MirelSIG** [comment]
Si por favor... con las disculpas por no haberlo hecho. Ademas me da luces
de por que no he podido cargar el geopackage de Mi Proyecto de Analisis
Espacial

**Comment by geofis** [comment]
Perfecto.
